# Generated by Django 5.2.8 on 2026-01-25 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Wolf', 'Wolf'), ('Fox', 'Fox'), ('Deer', 'Deer'), ('Bear', 'Bear'), ('Owl', 'Owl')], max_length=20)),
                ('habitat', models.CharField(max_length=50)),
                ('activity_cycle', models.CharField(max_length=50)),
                ('personality', models.CharField(max_length=50)),
                ('preference', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('animal1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_from', to='core.animalprofile')),
                ('animal2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_to', to='core.animalprofile')),
            ],
        ),
    ]
