# Generated by Django 5.2.8 on 2026-01-25 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='bonding_style',
            field=models.CharField(choices=[('Slow', 'Slow'), ('Balanced', 'Balanced'), ('Fast', 'Fast')], default='Balanced', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='diet',
            field=models.CharField(choices=[('Herbivore', 'Herbivore'), ('Carnivore', 'Carnivore'), ('Omnivore', 'Omnivore')], default='Omnivore', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='energy_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='favorite_activity',
            field=models.CharField(default='Exploring', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='social_style',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Pack', 'Pack'), ('Mixed', 'Mixed')], default='Solo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='territory',
            field=models.CharField(default='Forest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='preference',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='species',
            field=models.CharField(choices=[('Wolf', 'Wolf'), ('Fox', 'Fox'), ('Deer', 'Deer'), ('Bear', 'Bear'), ('Owl', 'Owl'), ('Rabbit', 'Rabbit'), ('Tiger', 'Tiger'), ('Lion', 'Lion')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Bond',
        ),
    ]
