# Generated by Django 5.2.8 on 2026-01-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animalprofile_age_animalprofile_bonding_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bonds', to='core.animalprofile')),
                ('to_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bonds', to='core.animalprofile')),
            ],
        ),
    ]
