# Generated by Django 5.2.8 on 2026-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bond'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
