# Generated by Django 5.2.8 on 2026-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animalprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bond',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
