# Generated by Django 5.2.8 on 2026-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
