# Generated by Django 5.2.8 on 2026-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_animalprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='diet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='species',
            field=models.CharField(max_length=50),
        ),
    ]
