# Generated by Django 5.2.8 on 2026-01-26 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_animalprofile_diet_alter_animalprofile_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
